#!/usr/bin/ruby
#
# Author:: Johannes Krude
# Copyright:: (c) Johannes Krude 2008
# License:: AGPL3
#
#--
# This file is part of multitris.
#
# multitris is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# multitris is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with multitris.  If not, see <http://www.gnu.org/licenses/>.
#++

require 'socket'
require 'multitris/gameboard'
require 'multitris/clientconcentrator'
require 'multitris/guiconcentrator'
require 'multitris/guilog'

require 'games/example'
require 'games/maze'

games= Hash.new
games["example"]= Games::Example
games["maze"]= Games::Maze

unless ARGV.size >= 3
	STDERR.puts "usage: ./gameserver guiport clientport game"
	STDERR.puts
	STDERR.puts "The following games are available:"
	games.each do |name, game|
		STDERR.puts "\t#{name} #{game.format_args}"
	end
	exit 1
end

gameboard= Multitris::GameBoard.new

logs= Multitris::GUILog.new
gameboard.add_observer(logs)

gui_concentrator= Multitris::GUIConcentrator.new(gameboard)

Thread.new do
	guis= TCPServer.new(ARGV[0])
	while gui= guis.accept
		gui_concentrator.addGUI(gui)
	end
end

client_concentrator= Multitris::ClientConcentrator.new

Thread.new do
	clients= TCPServer.new(ARGV[1])
	while client= clients.accept
		client_concentrator.addClient(client)
	end
end

game= games[ARGV[2]].new(gameboard, client_concentrator, *ARGV[3..-1])

loop do
	sleep(1)
end

