#!/usr/bin/ruby
#
# Author:: Johannes Krude
# Copyright:: (c) Johannes Krude 2008
# License:: AGPL3
#
#--
# This file is part of multitris.
#
# multitris is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# multitris is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with multitris.  If not, see <http://www.gnu.org/licenses/>.
#++

PORT= 12345

require 'client'
require 'httpserver'
require 'pathname'

if ARGV.size != 2
	STDERR.puts "usage: ./ruby-web server port"
	exit 1
end

webserver= HTTPServer.new("multitris-web")
webserver.listen(PORT) do |filename, vars|
	case filename
	when "command"
	when "play"
		unless vars["form-data"] and vars["form-data"]["username"] and vars["form-data"]["passphrase"]
			puts vars["form-data"]
			next HTTPServer::put_file("pages/default.html")
		end
	else
		p= Pathname.new(filename)
		if (if p= p.basename
			p= Pathname.new("pages") + p
		end) and p.file?
			HTTPServer::put_file(p.to_s)
		else
			HTTPServer::put_file("pages/default.html")
		end
	end
end
client= Multitris::Client.new

control= false

begin
	client.connect(ARGV[0], ARGV[1]) do |message|
		case message
		when "GOFORREST"
			control= true
		when "PLONK"
			control= false
		when /^ATTENTION (\w\w\w\w\w\w) (\d+)$/
			puts "You are player number #{$2}"
			puts "Your color is ##{$1}"
		else
			puts message
		end
	end
rescue Errno::ECONNREFUSED
	STDERR.puts "Connection refused"
	exit 2
end
exit

